In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("electricity_consumption_based_weather_dataset.csv")
df.head(4)

         date  AWND  PRCP  TMAX  TMIN  daily_consumption
0  2006-12-16   2.5   0.0  10.6   5.0           1209.176
1  2006-12-17   2.6   0.0  13.3   5.6           3390.460
2  2006-12-18   2.4   0.0  15.0   6.7           2203.826
3  2006-12-19   2.4   0.0   7.2   2.2           1666.194

In [6]:
print(df.size)
print(df.shape)

8598
(1433, 6)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1433 entries, 0 to 1432
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1433 non-null   str
 1   AWND               1418 non-null   float64
 2   PRCP               1433 non-null   float64
 3   TMAX               1433 non-null   float64
 4   TMIN               1433 non-null   float64
 5   daily_consumption  1433 non-null   float64
dtypes: float64(5), str(1)
memory usage: 81.3 KB

In [8]:
#converting date column from string/ object to date
df["date"] = pd.to_datetime(df['date'], errors='coerce')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1433 entries, 0 to 1432
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1433 non-null   datetime64[us]
 1   AWND               1418 non-null   float64
 2   PRCP               1433 non-null   float64
 3   TMAX               1433 non-null   float64
 4   TMIN               1433 non-null   float64
 5   daily_consumption  1433 non-null   float64
dtypes: datetime64[us](1), float64(5)
memory usage: 67.3 KB

In [9]:
df.describe()

,date,AWND,PRCP,TMAX,TMIN,daily_consumption
count,1433,1418.000000,1433.000000,1433.000000,1433.000000,1433.000000
mean,2008-12-02 20:05:51.709700,2.642313,3.800488,17.187509,9.141242,1561.078061
min,2006-12-16 00:00:00,0.000000,0.000000,-8.900000,-14.400000,14.218000
25%,2007-12-10 00:00:00,1.800000,0.000000,8.900000,2.200000,1165.700000
50%,2008-12-02 00:00:00,2.400000,0.000000,17.800000,9.400000,1542.650000
75%,2009-11-26 00:00:00,3.300000,1.300000,26.100000,17.200000,1893.608000
max,2010-11-26 00:00:00,10.200000,192.300000,39.400000,27.200000,4773.386000
std,NaN,1.140021,10.973436,10.136415,9.028417,606.819667

In [10]:
df.isnull().sum()

date                  0
AWND                 15
PRCP                  0
TMAX                  0
TMIN                  0
daily_consumption     0
dtype: int64

In [11]:
for col in df.columns:
  if df[col].isnull().sum() > 0 and col != "date":
    n = df[col].isnull().sum()
    df[col] = df[col].interpolate(method= "linear")
    print(f"filled {n} missing values in {col} column")
df.info()

filled 15 missing values in AWND column
<class 'pandas.DataFrame'>
RangeIndex: 1433 entries, 0 to 1432
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1433 non-null   datetime64[us]
 1   AWND               1433 non-null   float64
 2   PRCP               1433 non-null   float64
 3   TMAX               1433 non-null   float64
 4   TMIN               1433 non-null   float64
 5   daily_consumption  1433 non-null   float64
dtypes: datetime64[us](1), float64(5)
memory usage: 67.3 KB

In [12]:
print(f"we have {df.duplicated().sum()} duplicates")
print(f"we have {df['date'].duplicated().sum()} duplicated dates")

we have 0 duplicates
we have 0 duplicated dates

In [13]:
df_sorted = df.sort_values(by = 'date')
print(df_sorted.head(4))
df.head(4)

        date  AWND  PRCP  TMAX  TMIN  daily_consumption
0 2006-12-16   2.5   0.0  10.6   5.0           1209.176
1 2006-12-17   2.6   0.0  13.3   5.6           3390.460
2 2006-12-18   2.4   0.0  15.0   6.7           2203.826
3 2006-12-19   2.4   0.0   7.2   2.2           1666.194

        date  AWND  PRCP  TMAX  TMIN  daily_consumption
0 2006-12-16   2.5   0.0  10.6   5.0           1209.176
1 2006-12-17   2.6   0.0  13.3   5.6           3390.460
2 2006-12-18   2.4   0.0  15.0   6.7           2203.826
3 2006-12-19   2.4   0.0   7.2   2.2           1666.194

In [14]:
full_range = pd.date_range(df_sorted['date'].min(),(df_sorted['date']).max())
missing_dates = full_range.difference(df_sorted['date'])
print(missing_dates)

DatetimeIndex(['2007-04-29', '2009-06-14', '2010-01-13', '2010-08-18',
               '2010-08-19', '2010-08-20', '2010-08-21', '2010-09-26',
               '2010-09-27'],
              dtype='datetime64[us]', freq=None)

In [15]:
wrong_temp = df_sorted[df_sorted['TMIN']>df_sorted['TMAX']]
print(f"we have {len(wrong_temp)} wrong recorded tempratures")

for col in ["daily_consumption","PRCP","AWND"]:
  print(f"we have {(df_sorted[col]<0).sum()} nergative values in {col} columns")

q1 = df_sorted['daily_consumption'].quantile(0.25)
q3 = df_sorted['daily_consumption'].quantile(0.75)
iqr = q3-q1
lower_bound = q1 - 1.5*iqr
upper_bound = q3 + 1.5*iqr
outliers = df_sorted[(df_sorted['daily_consumption']<lower_bound) | (df_sorted['daily_consumption']>upper_bound)]

print(outliers.shape)
print(outliers.head(4))

we have 0 wrong recorded tempratures
we have 0 nergative values in daily_consumption columns
we have 0 nergative values in PRCP columns
we have 0 nergative values in AWND columns
(34, 6)
         date  AWND  PRCP  TMAX  TMIN  daily_consumption
1  2006-12-17   2.6   0.0  13.3   5.6           3390.460
7  2006-12-23   3.0  19.8  15.0   8.9           4773.386
10 2006-12-26   3.3   2.0  11.7   6.1           3934.110
13 2006-12-29   2.1   0.0   8.9   2.8           3174.392

In [16]:
df_sorted = df.set_index('date').reindex(full_range).rename_axis('date').reset_index()
df_sorted = df_sorted.interpolate(method='linear')

print(df_sorted.shape)
df_sorted.head(4)

(1442, 6)

        date  AWND  PRCP  TMAX  TMIN  daily_consumption
0 2006-12-16   2.5   0.0  10.6   5.0           1209.176
1 2006-12-17   2.6   0.0  13.3   5.6           3390.460
2 2006-12-18   2.4   0.0  15.0   6.7           2203.826
3 2006-12-19   2.4   0.0   7.2   2.2           1666.194

In [17]:
print("number of duplicated rowa is: ",df_sorted.duplicated().sum())
print()
print(df_sorted.info())

number of duplicated rowa is:  0

<class 'pandas.DataFrame'>
RangeIndex: 1442 entries, 0 to 1441
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1442 non-null   datetime64[us]
 1   AWND               1442 non-null   float64
 2   PRCP               1442 non-null   float64
 3   TMAX               1442 non-null   float64
 4   TMIN               1442 non-null   float64
 5   daily_consumption  1442 non-null   float64
dtypes: datetime64[us](1), float64(5)
memory usage: 67.7 KB
None

In [18]:
import matplotlib.pyplot as plt

fig, axis = plt.subplots(2,2,figsize=(20,10))

axis[0,0].plot(df_sorted['date'],df_sorted['daily_consumption'])
axis[0,0].set_title("daily consumption over time")

axis[0,1].hist(df_sorted['daily_consumption'],bins = 30)
axis[0,1].set_title("distribution of daily consumpution")

axis[1,0].scatter(df_sorted['TMAX'],df_sorted['daily_consumption'])
axis[1,0].set_title("daily consumption vs max temp")

axis[1,1].boxplot(df_sorted['daily_consumption'].dropna())
axis[1,1].set_title("boxplot of daily consumption")

plt.show()

C:\Users\hp\AppData\Local\Temp\ipykernel_24868\745170682.py:17: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [19]:
df = df_sorted
df['day_of_week'] = df['date'].dt.dayofweek
df['month'] = df['date'].dt.month
df["is_weekend"] = df["day_of_week"].isin([5,6]).astype(int)

print(df[['date','day_of_week','month','is_weekend']].head(4))

        date  day_of_week  month  is_weekend
0 2006-12-16            5     12           1
1 2006-12-17            6     12           1
2 2006-12-18            0     12           0
3 2006-12-19            1     12           0

In [20]:
df['consumpution_lag_1'] = df['daily_consumption'].shift(1)
df['consumpution_lag_7'] = df['daily_consumption'].shift(7)
df[["date","daily_consumption","consumpution_lag_1","consumpution_lag_7"]].head(10)

        date  daily_consumption  consumpution_lag_1  consumpution_lag_7
0 2006-12-16           1209.176                 NaN                 NaN
1 2006-12-17           3390.460            1209.176                 NaN
2 2006-12-18           2203.826            3390.460                 NaN
3 2006-12-19           1666.194            2203.826                 NaN
4 2006-12-20           2225.748            1666.194                 NaN
5 2006-12-21           1716.624            2225.748                 NaN
6 2006-12-22           2341.338            1716.624                 NaN
7 2006-12-23           4773.386            2341.338            1209.176
8 2006-12-24           2550.012            4773.386            3390.460
9 2006-12-25           2743.120            2550.012            2203.826

In [21]:
df['rolling_mean_7'] = df['daily_consumption'].rolling(window=7).mean()
df['rolling_max_7'] = df['daily_consumption'].rolling(window=7).max()

df['temp_range'] = (df['TMAX'] - df['TMIN'])
df[['date','temp_range','daily_consumption','rolling_mean_7','rolling_max_7']].head(10)

        date  temp_range  daily_consumption  rolling_mean_7  rolling_max_7
0 2006-12-16         5.6           1209.176             NaN            NaN
1 2006-12-17         7.7           3390.460             NaN            NaN
2 2006-12-18         8.3           2203.826             NaN            NaN
3 2006-12-19         5.0           1666.194             NaN            NaN
4 2006-12-20         6.1           2225.748             NaN            NaN
5 2006-12-21         8.9           1716.624             NaN            NaN
6 2006-12-22         5.5           2341.338     2107.623714       3390.460
7 2006-12-23         6.1           4773.386     2616.796571       4773.386
8 2006-12-24         5.0           2550.012     2496.732571       4773.386
9 2006-12-25         3.3           2743.120     2573.774571       4773.386

In [22]:
before = df.shape[0]
df = df.dropna().reset_index(drop = True)
after = df.shape[0]
print(f"we have {before-after} rows with missing values")
df.shape

we have 7 rows with missing values

(1435, 14)

In [23]:
splite = int(len(df)*0.8)
training = df.iloc[:splite]
testing = df.iloc[splite:]

print(f" training start from {training['date'].min()} and ends at {training['date'].max()} with {len(training)} rows")
print(f" testing start from {testing['date'].min()} and ends at {testing['date'].max()} with {len(testing)} rows")

 training start from 2006-12-23 00:00:00 and ends at 2010-02-12 00:00:00 with 1148 rows
 testing start from 2010-02-13 00:00:00 and ends at 2010-11-26 00:00:00 with 287 rows

In [24]:
features_col = ['AWND', 'PRCP', 'TMAX', 'TMIN','day_of_week', 'month',
                'is_weekend', 'consumpution_lag_1',
                'consumpution_lag_7', 'rolling_mean_7', 'rolling_max_7']

In [25]:
X_train = training[features_col]
y_train = training['daily_consumption']

X_test = testing[features_col]
y_test = testing['daily_consumption']

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

lr = LinearRegression()
lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)

mae_lr = mean_absolute_error(y_test,y_pred)
rmse_lr = np.sqrt(mean_squared_error(y_test,y_pred))
mape_lr = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
r2_lr = r2_score(y_test,y_pred)

print('Lenier Regression Metrics:')
print(f'Mean Absolute Error (MAE): {mae_lr:.2f}')
print(f'Root Mean Squared Error (RMSE): {rmse_lr:.2f}')
print(f'Mean Absolute Percentage Error (MAPE): {mape_lr:.2f}%')

Lenier Regression Metrics:
Mean Absolute Error (MAE): 249.44
Root Mean Squared Error (RMSE): 348.30
Mean Absolute Percentage Error (MAPE): 32.54%

In [27]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
mae_rf = mean_absolute_error(y_test, y_pred)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred))
mape_rf = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
r2_rf = r2_score(y_test, y_pred)

print('Random Forest Metrics:')
print(f'Mean Absolute Error (MAE): {mae_rf:.2f}')
print(f'Root Mean Squared Error (RMSE): {rmse_rf:.2f}')
print(f'Mean Absolute Percentage Error (MAPE): {mape_rf:.2f}%')

Random Forest Metrics:
Mean Absolute Error (MAE): 225.95
Root Mean Squared Error (RMSE): 317.21
Mean Absolute Percentage Error (MAPE): 27.80%

In [28]:
feature_impotance = pd.DataFrame({'feature': features_col, 'importance': rf.feature_importances_})
feature_impotance = feature_impotance.sort_values('importance', ascending=False)
print(feature_impotance)

               feature  importance
9       rolling_mean_7    0.572406
10       rolling_max_7    0.097012
7   consumpution_lag_1    0.078442
8   consumpution_lag_7    0.054137
4          day_of_week    0.042086
6           is_weekend    0.033453
0                 AWND    0.033145
2                 TMAX    0.030928
3                 TMIN    0.027354
5                month    0.017721
1                 PRCP    0.013315

In [29]:
plt.figure(figsize = (10,3))
plt.plot(testing['date'],y_test.values, label = "actual", color = 'yellow')
plt.plot(testing['date'],y_pred, label = "predicted", color = 'red')
plt.xlabel("date")
plt.ylabel("daily consumption")
plt.legend()
plt.show()

C:\Users\hp\AppData\Local\Temp\ipykernel_24868\827888827.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [30]:
import joblib

joblib.dump(rf, 'random_forest_model.joblib')
print('model saved')

model saved